[package]
name = "syf"
version = "0.1.0"
authors = ["Nick <dev@nsenger.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.4"
futures = "0.3.4"
tokio = "0.2.13"
scraper = "0.11.0"
